apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    meta.helm.sh/release-name: statepool
    meta.helm.sh/release-namespace: statepool-keda
  creationTimestamp: "2026-08-26T18:38:50Z"
  finalizers:
  - finalizer.keda.sh
  generation: 2
  labels:
    app.kubernetes.io/instance: statepool
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rwkv-statepool
    app.kubernetes.io/version: 0.3.0-beta.2
    scaledobject.keda.sh/name: statepool-worker
  name: statepool-worker
  namespace: statepool-keda
  resourceVersion: "4078"
  uid: f02553a2-99ac-4bb1-bbd4-81e81e230e4b
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          policies:
          - periodSeconds: 60
            type: Pods
            value: 1
          stabilizationWindowSeconds: 10
    restoreToOriginalReplicaCount: true
    scalingModifiers: {}
  cooldownPeriod: 10
  idleReplicaCount: 0
  initialCooldownPeriod: 0
  maxReplicaCount: 3
  minReplicaCount: 0
  pollingInterval: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: statepool-worker
  triggers:
  - metadata:
      activationThreshold: "0"
      ignoreNullValues: "false"
      metricName: rwkv_statepool_pending_requests
      query: sum(statepool_pending_requests)
      serverAddress: http://prometheus.statepool-keda.svc.cluster.local:9090
      threshold: "1"
    metricType: AverageValue
    type: prometheus
  - metadata:
      activationThreshold: "0"
      ignoreNullValues: "false"
      metricName: rwkv_statepool_estimated_decode_seconds
      query: sum(statepool_estimated_decode_seconds)
      serverAddress: http://prometheus.statepool-keda.svc.cluster.local:9090
      threshold: "999999"
    metricType: AverageValue
    type: prometheus
status:
  authenticationsTypes: ""
  conditions:
  - message: ScaledObject is defined correctly and is ready for scaling
    reason: ScaledObjectReady
    status: "True"
    type: Ready
  - message: Scaling is not performed because triggers are not active
    reason: ScalerNotActive
    status: "False"
    type: Active
  - message: No fallbacks are active on this scaled object
    reason: NoFallbackFound
    status: "False"
    type: Fallback
  - status: "False"
    type: Paused
  externalMetricNames:
  - s0-prometheus
  - s1-prometheus
  hpaName: keda-hpa-statepool-worker
  lastActiveTime: "2026-08-26T18:47:52Z"
  originalReplicaCount: 0
  scaleTargetGVKR:
    group: apps
    kind: Deployment
    resource: deployments
    version: v1
  scaleTargetKind: apps/v1.Deployment
  triggersActivity:
    s0-prometheus:
      isActive: false
    s1-prometheus:
      isActive: false
  triggersTypes: prometheus
