{{- if .Values.plugin.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rwkv-statepool.fullname" . }}-state
  labels:
    {{- include "rwkv-statepool.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.plugin.persistence.storageClass }}
  storageClassName: {{ .Values.plugin.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.plugin.persistence.size }}
{{- end }}
