{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rwkv-statepool.fullname" . }}-worker
  labels:
    {{- include "rwkv-statepool.labels" . | nindent 4 }}
    app.kubernetes.io/component: inference-worker
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ include "rwkv-statepool.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: inference-worker
  ports:
    - name: inference
      port: {{ .Values.worker.port }}
      targetPort: inference
{{- end }}
